//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оплата.
    /// </summary>
    // *** Start programmer edit section *** (Оплата CustomAttributes)

    // *** End programmer edit section *** (Оплата CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОплатаE", new string[] {
            "ВидОплаты as \'Вид оплаты\'",
            "Стоимость as \'Стоимость\'",
            "Время as \'Время\'",
            "Дата as \'Дата\'",
            "ПечатьФото as \'Печать фото\'",
            "ПечатьФото.НомерЗаказа as \'Номер заказа\'"}, Hidden=new string[] {
            "ПечатьФото.НомерЗаказа"})]
    [MasterViewDefineAttribute("ОплатаE", "ПечатьФото", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЗаказа")]
    [View("ОплатаL", new string[] {
            "ВидОплаты as \'Вид оплаты\'",
            "Стоимость as \'Стоимость\'",
            "Время as \'Время\'",
            "Дата as \'Дата\'",
            "ПечатьФото.НомерЗаказа as \'Номер заказа\'"})]
    public class Оплата : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Kursovaya5.ТипОплаты fВидОплаты;
        
        private int fСтоимость;
        
        private string fВремя;
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya5.ПечатьФото fПечатьФото;
        
        // *** Start programmer edit section *** (Оплата CustomMembers)

        // *** End programmer edit section *** (Оплата CustomMembers)

        
        /// <summary>
        /// ВидОплаты.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.ВидОплаты CustomAttributes)

        // *** End programmer edit section *** (Оплата.ВидОплаты CustomAttributes)
        public virtual IIS.Kursovaya5.ТипОплаты ВидОплаты
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.ВидОплаты Get start)

                // *** End programmer edit section *** (Оплата.ВидОплаты Get start)
                IIS.Kursovaya5.ТипОплаты result = this.fВидОплаты;
                // *** Start programmer edit section *** (Оплата.ВидОплаты Get end)

                // *** End programmer edit section *** (Оплата.ВидОплаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.ВидОплаты Set start)

                // *** End programmer edit section *** (Оплата.ВидОплаты Set start)
                this.fВидОплаты = value;
                // *** Start programmer edit section *** (Оплата.ВидОплаты Set end)

                // *** End programmer edit section *** (Оплата.ВидОплаты Set end)
            }
        }
        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Время CustomAttributes)

        // *** End programmer edit section *** (Оплата.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Время Get start)

                // *** End programmer edit section *** (Оплата.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (Оплата.Время Get end)

                // *** End programmer edit section *** (Оплата.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Время Set start)

                // *** End programmer edit section *** (Оплата.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (Оплата.Время Set end)

                // *** End programmer edit section *** (Оплата.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Дата CustomAttributes)

        // *** End programmer edit section *** (Оплата.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Дата Get start)

                // *** End programmer edit section *** (Оплата.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Оплата.Дата Get end)

                // *** End programmer edit section *** (Оплата.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Дата Set start)

                // *** End programmer edit section *** (Оплата.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Оплата.Дата Set end)

                // *** End programmer edit section *** (Оплата.Дата Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Оплата.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.Стоимость Get start)

                // *** End programmer edit section *** (Оплата.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (Оплата.Стоимость Get end)

                // *** End programmer edit section *** (Оплата.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.Стоимость Set start)

                // *** End programmer edit section *** (Оплата.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Оплата.Стоимость Set end)

                // *** End programmer edit section *** (Оплата.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Оплата.
        /// </summary>
        // *** Start programmer edit section *** (Оплата.ПечатьФото CustomAttributes)

        // *** End programmer edit section *** (Оплата.ПечатьФото CustomAttributes)
        [PropertyStorage(new string[] {
                "ПечатьФото"})]
        [NotNull()]
        public virtual IIS.Kursovaya5.ПечатьФото ПечатьФото
        {
            get
            {
                // *** Start programmer edit section *** (Оплата.ПечатьФото Get start)

                // *** End programmer edit section *** (Оплата.ПечатьФото Get start)
                IIS.Kursovaya5.ПечатьФото result = this.fПечатьФото;
                // *** Start programmer edit section *** (Оплата.ПечатьФото Get end)

                // *** End programmer edit section *** (Оплата.ПечатьФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оплата.ПечатьФото Set start)

                // *** End programmer edit section *** (Оплата.ПечатьФото Set start)
                this.fПечатьФото = value;
                // *** Start programmer edit section *** (Оплата.ПечатьФото Set end)

                // *** End programmer edit section *** (Оплата.ПечатьФото Set end)
            }
        }
        
        // *** Start programmer edit section *** (Оплата.Печать CustomAttributes)

        // *** End programmer edit section *** (Оплата.Печать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Печать()
        {
            // *** Start programmer edit section *** (Оплата.Печать method implementation)

            return;
            // *** End programmer edit section *** (Оплата.Печать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОплатаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаE", typeof(IIS.Kursovaya5.Оплата));
                }
            }
            
            /// <summary>
            /// "ОплатаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОплатаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОплатаL", typeof(IIS.Kursovaya5.Оплата));
                }
            }
        }
    }
}
